on:
  push:
    branches:
      -"*"


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: -ls -la
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run : python --version